server:
  port: 9258

spring:
  datasource:
    url: jdbc:mysql://185.227.152.145:3306/yushi
    username: root
    password: makai123
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/
#  mvc:
#    view:
#      prefix: /views/
#      suffix: .jsp
#  web:
#    resources:
#      static-locations: classpath:static
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.me.dao: debug




